#include "model/formulas.hpp"

#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
#include <doctest.hpp>

// DISCLAIMER: These test cases were generated by Google Gemini via Antigravity.
//             Some tests were then hand modified, the rest do a fine job fine as is.

TEST_CASE("entity_energy_change full intake when age 0")
{
    double change = fatint::model::entity_energy_change(0, 10.0, 0.9, 5.0);
    CHECK(change == doctest::Approx(5.0));
}

TEST_CASE("entity_energy_change discounted intake when aged")
{
    double change = fatint::model::entity_energy_change(1, 10.0, 0.9, 5.0);
    CHECK(change == doctest::Approx(4));

    change = fatint::model::entity_energy_change(2, 10.0, 0.9, 5.0);
    CHECK(change == doctest::Approx(3.1));

    change = fatint::model::entity_energy_change(10, 10.0, 0.9, 5.0);
    CHECK(change == doctest::Approx(-1.513216));
}

TEST_CASE("offspring_count - perfect similarity")
{
    int count = fatint::model::offspring_count(0, 5.0, 5.0, 1.0);
    CHECK(count == 10);
}

TEST_CASE("offspring_count - high similarity")
{
    int count = fatint::model::offspring_count(1.0, 5.0, 5.0, 1.0);
    CHECK(count == 9);
}

TEST_CASE("offspring_count - high similarity, low slope")
{
    int count = fatint::model::offspring_count(1.0, 5.0, 5.0, 0.5);
    CHECK(count == 7);
}

TEST_CASE("offspring_count - low similarity")
{
    int count = fatint::model::offspring_count(4.0, 5.0, 5.0, 1.0);
    CHECK(count == 6);
}

TEST_CASE("offspring_count - incompatble pair")
{
    int count = fatint::model::offspring_count(10.0, 5.0, 5.0, 1.0);
    CHECK(count == 0);
}

TEST_CASE("stretch_gene with stretching factor")
{
    // Stretch factor of 2.0 doubles the value
    int result = fatint::model::stretch_gene(5, 0, 10, 2.0);
    CHECK(result == 10); // 0 + floor(5 * 2.0) % 11 = 0 + 10 = 10
}

TEST_CASE("stretch_gene wraps around")
{
    // Should wrap around when stretched value exceeds max
    int result = fatint::model::stretch_gene(10, 0, 10, 2.0);
    CHECK(result == 9); // 0 + floor(10 * 2.0) % 11 = 0 + 20 % 11 = 9
}

TEST_CASE("stretch_gene with offset min")
{
    // v_min is not zero
    int result = fatint::model::stretch_gene(5, 10, 20, 1.0);
    CHECK(result == 15); // 10 + floor(5 * 1.0) % 11 = 10 + 5 = 15
}
