@startuml
class Simulator {
  - const ISimilarity similarity
  - const ISelection selection
  - const IReproduction reproduction
  - const IGeneAdder gene_adder
  - const ISpeciesCounter species_counter
  - const RunParameters parameters
  + RunStates run(&rng)
}

class Random {
  - pimpl
  + Random(seed)
  + void seed(s)
  + bool chance(p)
  + int random(min, max)
  + void shuffle(&vec)
  + vector<int> random_indices(count)
}

interface ISimilarity {
  + bool compatible(a, b) const
  + int offspring_count(a, b) const
}
interface ISelection {
  + int? select(&rng, population, subject_index) const
}
interface IMutation {
  + void mutate(&rng, &genotype) const
}
interface ICombination {
  + void combine(&rng, a, b, &out) const
}
interface IReproduction {
  + bool reproduce(&rng, a, b, &offspring) const
}
interface IGeneAdder {
  + void add_gene(&rng, &genotype) const
}
interface ISpeciesCounter {
  + int count_species(population) const
}

class EuclideanDistanceSimilarity {
    - ReproductionParameters parameters
    + bool compatible(a, b) const
    + int offspring_count(a, b) const
}
class ReservoirSelection {
    - const ISimilarity similarity
    + int? select(&rng, population, subject_index) const
}
class BoundedMutation {
    - double p_mutation
    - double v_mutation
    + void mutate(&rng, &genotype) const
}
class Crossover {
    - double p_crossing
    + void combine(&rng, a, b, &out) const
}
class GeneticReproduction {
    - const IMutation mutation
    - const ICrossover crossover
    + bool reproduce(&rng, a, b, &offspring) const
}
class RandomGeneAdder {
    - int v_min
    - int v_max
    + void add_gene(&rng, &genotype) const
}
class VStretchGeneAdder {
    - int v_min
    - int v_max
    - double v_stretch
    + void add_gene(&rng, &genotype) const
}
class DepthFirstSearchSpeciesCounter {
    - const ISimilarity similarity
    + int count_species(population) const
}
class DisjointSetsSpeciesCounter {
    - const ISimilarity similarity
    + int count_species(population) const
}

class ReservoirSampling<T> {
    - T? current
    - int n
    + reset()
    + T? get()
    + void add(&rng, t)
}

Simulator *-- ISimilarity
Simulator *-- ISelection
Simulator *-- IReproduction
Simulator *-- IGeneAdder
Simulator *-- ISpeciesCounter
Simulator *-- RunParameters

ISimilarity <|-- EuclideanDistanceSimilarity
ISelection <|-- ReservoirSelection
IReproduction <|-- GeneticReproduction
IGeneAdder <|-- RandomGeneAdder
IGeneAdder <|-- VStretchGeneAdder
ISpeciesCounter <|-- DepthFirstSearchSpeciesCounter
ISpeciesCounter <|-- DisjointSetsSpeciesCounter

ReservoirSelection --> ReservoirSampling

GeneticReproduction *-- IMutation
GeneticReproduction *-- ICombination

IMutation <|-- BoundedMutation
ICombination <|-- Crossover

ReservoirSampling --> Random
RandomGeneAdder --> Random
Crossover --> Random
BoundedMutation --> Random
@enduml
