@startuml
hide empty description

[*] --> argv : main()
argv --> ExperimentSweepParameters : parse_args()
ExperimentSweepParameters --> ExperimentParameters : ExperimentSweepParameters::expand()
ExperimentParameters --> RunParameters : ExperimentParameters::expand()
RunParameters --> RunStates : Simulator::run()
RunStates --> ExperimentResults : measure()
ExperimentResults --> ExperimentSweepResults : measure()
ExperimentSweepResults --> fájl : IOOutputWriter::write()
@enduml
