@startuml
participant Main
participant Simulator
participant StatisticsEvaluator
participant IOutputWriter

Main ->> ExperimentSweep : ExperimentSweepParameters
ExperimentSweep ->> Experiment : ExperimentParameters
Experiment ->> Simulator : RunParameters
Simulator ->> Experiment : RunStates
Experiment ->> ExperimentSweep : ExperimentStates
ExperimentSweep ->> Main : ExperimentSweepStates
Main ->> StatisticsEvaluator : ExperimentSweepStates
StatisticsEvaluator ->> Main : ExperimentSweepResults
Main ->> IOutputWriter : ExperimentSweepResults
@enduml
