name: Build thesis
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v6
      - name: Install dependencies
        id: setup
        run: |
          sudo apt-get update
          sudo apt-get upgrade -y
          sudo apt-get install -y wget xz-utils build-essential cmake
          mkdir -p /opt/typst
          cd /opt/typst
          wget https://github.com/typst/typst/releases/download/v0.14.2/typst-x86_64-unknown-linux-musl.tar.xz
          tar -xf ./*.tar.xz
          mkdir /opt/NetLogo
          cd /opt/NetLogo
          wget https://downloads.netlogo.org/6.4.0/NetLogo-6.4.0-64.tgz
          tar -xzf ./*.tgz
      - name: Compile libfatint
        id: compile-libfatint
        run: |
          cmake -S fatint-cpp -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --parallel --config Release
      - name: Run simularions
        id: run-simulaions
        run: |
          export PATH=$PATH:$PWD/build/:$PWD/build/libs/libfatint/tests:/opt/NetLogo/NetLogo-6.4.0-64:/opt/typst/typst-x86_64-unknown-linux-musl
          ./run-simulations.sh
      - name: Compile thesis
        id: compile-thesis
        run: |
          export PATH=$PATH:/opt/typst/typst-x86_64-unknown-linux-musl
          typst compile thesis/main.typ KL43GM.pdf
      - name: Export PDF
        id: export
        uses: actions/upload-artifact@v4
        with:
          name: thesis
          path: KL43GM.pdf
